### ISSUE TITLE
Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class com.gosuncn.mplay.RtspPlayer

### ISSUE THREAD

**Issue by zhengoogle** [huweijian5/RtspPlayer#2]
04-14 22:03:04.466 7960-7960/com.gosuncn.mpa E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.gosuncn.mpa, PID: 7960
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gosuncn.mpa/com.gosuncn.mpa.player1.TestPlayer1Activity}: android.view.InflateException: Binary XML file line #37: Error inflating class com.gosuncn.mplay.RtspPlayer
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class com.gosuncn.mplay.RtspPlayer
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
                                                                   at com.gosuncn.mpa.player1.TestPlayer1Activity.onCreate(TestPlayer1Activity.java:31)
                                                                   at android.app.Activity.performCreate(Activity.java:5342)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276) 
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261) 
                                                                   at com.gosuncn.mpa.player1.TestPlayer1Activity.onCreate(TestPlayer1Activity.java:31) 
                                                                   at android.app.Activity.performCreate(Activity.java:5342) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libmediandk.so" needed by "libstreamhandler-lib.so"; caused by library "libmediandk.so" not found
                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                   at java.lang.System.loadLibrary(System.java:555)
                                                                   at com.gosuncn.mplay.PlayerJNI.<clinit>(PlayerJNI.java:11)
                                                                   at com.gosuncn.mplay.RtspPlayer.<init>(RtspPlayer.java:65)
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276) 
                                                                   at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261) 
                                                                   at com.gosuncn.mpa.player1.TestPlayer1Activity.onCreate(TestPlayer1Activity.java:31) 
                                                                   at android.app.Activity.performCreate(Activity.java:5342) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by hijunmeng** [comment]
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libmediandk.so" needed by "libstreamhandler-lib.so"; caused by library "libmediandk.so" not found
这里面加了mediandk，因此需要运行在21以上的手机。
